optimizer: adam                    # adam
scheduler: inv_sqrt_decay          # inv_sqrt_decay
lr: 3e-4                           # 3e-4
weight_decay: 0.0                  # 0.0
betas: [0.9, 0.98]                 # [0.9, 0.98]
eps: 1e-8                          # 1e-8
lambda_val: 1.0                    # 1.0
dim: 256                           # 256
warmup_steps: 50                   # 50
no_decay_layers: ["bias", "emb", "norm"]
